name: Doxygen GitHub Pages Deploy Action

on:
  push:
#    branches:
#      - main
  workflow_dispatch:

env:
    BRANCH: gh-pages
    FOLDER: build/docs
    CONFIG_FILE: docs/Doxyfile

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: github.repository == 'Neo-Diamons/Arcade'
    steps:
      - uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get install doxygen graphviz -y

      - name: Create folder
        run: |
          mkdir -p build/docs

      - name: Generate Doxygen Documentation
        run: doxygen ${{ env.CONFIG_FILE }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH }}
          folder: ${{ env.FOLDER }}
          target-folder: .
