name: Doxygen GitHub Pages Deploy Action

on:
  push:
#    branches:
#      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: github.repository == 'Neo-Diamons/Arcade'
    steps:
      - uses: actions/checkout@v4
      - name: Create folder
        run: |
          mkdir build

      - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          config_file: docs/Doxyfile
          folder: build/docs
