name: Mirror

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  MIRROR_URL: 'git@github.com:EpitechPromo2027/B-OOP-400-REN-4-1-arcade-morgan.largeot.git'

jobs:
  push_to_mirror:
    runs-on: ubuntu-latest

    if: github.repository == 'Neo-Diamons/Arcade'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.SSH_MIRROR_KEY }}
